<a href="https://colab.research.google.com/github/danie033/Extra_Code/blob/main/python_refresh.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
x=[1,3,4]
print(x)
x.append(["repeated_word","something","repeated_word"])
print(x)

for i in range(3):
  x.append(f"Item{i}")


print(x)
new_dict={"something":"repeated_word",1:5,"another":4}
x.append(new_dict)
print(x)



[1, 3, 4]
[1, 3, 4, ['repeated_word', 'something', 'repeated_word']]
[1, 3, 4, ['repeated_word', 'something', 'repeated_word'], 'Item0', 'Item1', 'Item2']
[1, 3, 4, ['repeated_word', 'something', 'repeated_word'], 'Item0', 'Item1', 'Item2', {'something': 'repeated_word', 1: 5, 'another': 4}]


In [2]:
min=1
max=30

x=[np.random.randint(min,max) for _ in range(10)]
print(x)

print("The following numbers are even:")
z=[c for c in x if c%2==0]
print(z)
print(z[0])

[24, 27, 1, 18, 6, 4, 19, 5, 21, 22]
The following numbers are even:
[24, 18, 6, 4, 22]
24


In [3]:
n_dict={"something":"other","Daniel":"Andres","New Item":"Foo"}
n_dict2=n_dict
n_dict3=n_dict.copy()

print(n_dict)
print(n_dict2)
print(n_dict3)

n_dict.update({"something":"other2","new_input":"more"})

print("Updated dictionaries")
print(n_dict)
print(n_dict2)
print(n_dict3)

{'something': 'other', 'Daniel': 'Andres', 'New Item': 'Foo'}
{'something': 'other', 'Daniel': 'Andres', 'New Item': 'Foo'}
{'something': 'other', 'Daniel': 'Andres', 'New Item': 'Foo'}
Updated dictionaries
{'something': 'other2', 'Daniel': 'Andres', 'New Item': 'Foo', 'new_input': 'more'}
{'something': 'other2', 'Daniel': 'Andres', 'New Item': 'Foo', 'new_input': 'more'}
{'something': 'other', 'Daniel': 'Andres', 'New Item': 'Foo'}


In [4]:
print("Original Dictionary")
print(n_dict)
print("Printing Items:")
print(n_dict.items())
print("Printing values:")
print(n_dict.values())
print("Printing keys:")
print(n_dict.keys())

Original Dictionary
{'something': 'other2', 'Daniel': 'Andres', 'New Item': 'Foo', 'new_input': 'more'}
Printing Items:
dict_items([('something', 'other2'), ('Daniel', 'Andres'), ('New Item', 'Foo'), ('new_input', 'more')])
Printing values:
dict_values(['other2', 'Andres', 'Foo', 'more'])
Printing keys:
dict_keys(['something', 'Daniel', 'New Item', 'new_input'])


In [5]:
from_keys=dict.fromkeys(x,"Default")
print(from_keys)

{24: 'Default', 27: 'Default', 1: 'Default', 18: 'Default', 6: 'Default', 4: 'Default', 19: 'Default', 5: 'Default', 21: 'Default', 22: 'Default'}


In [6]:
for x,y in n_dict.items():
  print(f"""This is the key: "{x}" and this is the item: "{y}" """)

This is the key: "something" and this is the item: "other2" 
This is the key: "Daniel" and this is the item: "Andres" 
This is the key: "New Item" and this is the item: "Foo" 
This is the key: "new_input" and this is the item: "more" 


In [7]:
new_set={2,5,7,8,3,6,2,6}
print(new_set)

print(new_set.intersection({2,5}))

{2, 3, 5, 6, 7, 8}
{2, 5}


In [8]:
new_tuple=(1,3,5,"hello",4,new_set)

print(new_tuple)

(1, 3, 5, 'hello', 4, {2, 3, 5, 6, 7, 8})


In [9]:
new_tuple=tuple(np.sin(x) for x in range(5))

# for i in new_tuple:
#   print(i)

print(new_tuple)

(np.float64(0.0), np.float64(0.8414709848078965), np.float64(0.9092974268256817), np.float64(0.1411200080598672), np.float64(-0.7568024953079282))


Now I will be working with numpy

In [10]:
my_list=[2,4,6,8]
my_array=np.array(my_list)

print(my_list)
print(my_array)

print(type(my_array),my_array.shape,my_array[2])


[2, 4, 6, 8]
[2 4 6 8]
<class 'numpy.ndarray'> (4,) 6


In [11]:
my_array1=np.array([1,3,5,3])
my_array2=np.array([9,8,5,3])

#9+24+25+9=67
dot_product=my_array1.dot(my_array2)

print(dot_product)

A=np.ones((2,2))
C=np.ones((2,2))
B=np.eye(2)
print(A)
print(B)
print(C)

mul_A_B=A@C
print("multiplication:")
print(mul_A_B)



67
[[1. 1.]
 [1. 1.]]
[[1. 0.]
 [0. 1.]]
[[1. 1.]
 [1. 1.]]
multiplication:
[[2. 2.]
 [2. 2.]]


In [12]:
a = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])
b=a[:2,:2]
c=3*b.copy()
print("Printing a:")
print(a)
print("Printing b:")
print(b)

print("Printing more")
#changing b
b[1,1]=100
c[1,1]=200
print(b)
print(c)
print(a)

Printing a:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Printing b:
[[1 2]
 [5 6]]
Printing more
[[  1   2]
 [  5 100]]
[[  3   6]
 [ 15 200]]
[[  1   2   3   4]
 [  5 100   7   8]
 [  9  10  11  12]]


In [13]:
A=np.arange(4)
B=np.array([[1,3,6,2],
          [3,5,3,7],
          [63,59,7,0]])

print(B)
conditions=(B>3) & (B<60)
print(conditions)
print(B*conditions)

C=np.where((B>3) & (B<60),B,333)
print(C)
print(C.T)

print(C[2,:])

print("more of the element")
CC=np.tile(C[2,:],[3,1])
print(C)




[[ 1  3  6  2]
 [ 3  5  3  7]
 [63 59  7  0]]
[[False False  True False]
 [False  True False  True]
 [False  True  True False]]
[[ 0  0  6  0]
 [ 0  5  0  7]
 [ 0 59  7  0]]
[[333 333   6 333]
 [333   5 333   7]
 [333  59   7 333]]
[[333 333 333]
 [333   5  59]
 [  6 333   7]
 [333   7 333]]
[333  59   7 333]
more of the element
[[333 333   6 333]
 [333   5 333   7]
 [333  59   7 333]]


In [23]:
new_matrix=np.array([[1,3,5,3],[9,5,3,7],[5,7,8,4]])
print(new_matrix)
print("summation")
print(np.sum(new_matrix,axis=0))

[[1 3 5 3]
 [9 5 3 7]
 [5 7 8 4]]
summation
[15 15 16 14]


In [34]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]]) #4X3
y=np.array([3,3,3]) #has to be the same size as thenumber of columns 1X3
z=np.tile(y,(4,2))
print("Printing x:\n",x)
print("Printing y:\n",y)
print("Printing y:\n",z)

print(x+y)

Printing x:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Printing y:
 [3 3 3]
Printing y:
 [[3 3 3 3 3 3]
 [3 3 3 3 3 3]
 [3 3 3 3 3 3]
 [3 3 3 3 3 3]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [44]:
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5,7])    # w has shape (2,)
print("Printing v:\n",v)
print("Printing w:\n",w)
shaped=np.reshape(v,(3,1))
print("Printing shaped:\n",shaped)
print("Printing shaped2:\n",v.T)

print("printing outer product:\n",shaped*w)

print("printing outer product w/func:\n",np.outer(v,w))
print("printing outer product: w/func\n",np.outer(w,v))

Printing v:
 [1 2 3]
Printing w:
 [4 5 7]
Printing shaped:
 [[1]
 [2]
 [3]]
Printing shaped2:
 [1 2 3]
printing outer product:
 [[ 4  5  7]
 [ 8 10 14]
 [12 15 21]]
printing outer product:
 [[ 4  5  7]
 [ 8 10 14]
 [12 15 21]]
printing outer product w/func:
 [[ 4  5  7]
 [ 8 10 14]
 [12 15 21]]
printing outer product: w/func
 [[ 4  8 12]
 [ 5 10 15]
 [ 7 14 21]]
